apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # You can also use LoadBalancer or ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Optional, specify a port if using NodePort

