- name : slave 
  hosts: vm2
  remote_user: yusef
  become: yes 
  tasks:
     -name : update
      apt: 
      update_cashe: yes


     -naem: create director
      file:
        path: /home/ubuntu/jenkins_home
        state: directory
        mode: '0777'


     -naem: install openjdk
      apt:
        name: openjdk-8-jdk
        
